version: '3.1'

services:
  crud_db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: user
      POSTGRES_DB: crud
      POSTGRES_USER: user
    ports:
      - 5432:5432
